 # Site settings
title: AQUA WAIKIKI PEARL
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.aquawaikikipearl.com/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty

default_lang: 'en'
languages: ['en']

exclude: ['sitemap.json']
empty_array: []

booking_widget_url: https://pearlwaikiki.reztrip.com/mobile


data_paginate: 
  per_page: 5
  data: 'blog'
  path: 'blog/page:num'
  pagination_template: 'blog/index.html'
  sort_field: 'date'
  sort_reverse: true


#paginate_path: "/page:num/"
markdown: kramdown 

page_gen:
  - data: 'blog'
    template: 'blog-details'
    dir: 'blog'
